"""
Django settings for pecl project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
import os
import ssl
import sys
from pathlib import Path

from environ import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
if env.str("ECL_DJANGO_SECRET_KEY", None) is None:
    env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("ECL_DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env.bool("ECL_DJANGO_DEBUG", False)

ALLOWED_HOSTS = json.loads(os.environ.get("ECL_DJANGO_ALLOWED_HOSTS", default="[]"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
        },
    },
    "handlers": {
        "console": {"level": "INFO", "class": "logging.StreamHandler", "stream": sys.stdout, "formatter": "verbose"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "level": "INFO",
            "handlers": ["console"],
        }
    },
}

# Application definition

INSTALLED_APPS = [
    "channels",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "catalog",
    "agent",
    "account",
    "sync",
    "analytics",
    "drf_yasg",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pecl.urls"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

FILE_STORAGE = env.str("FILE_STORAGE", default="local")

if FILE_STORAGE == "local":
    DEFAULT_FILE_STORAGE = "pecl.storage.LocalStorage"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "pecl.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("ECL_CELERY_BROKER_URL")],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": env.str("ECL_DB_NAME"),
        "USER": env.str("ECL_DB_USER"),
        "PASSWORD": env.str("ECL_DB_PASSWORD"),
        "HOST": env.str("ECL_DB_HOST"),
        "PORT": env.str("ECL_DB_PORT"),
        "ATOMIC_REQUESTS": True,
    }
}

# ---- HTTPS & proxy (Heroku) ----
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SSL redirect: enabled in production, disabled in development
SECURE_SSL_REDIRECT = env.bool("ECL_SECURE_SSL_REDIRECT", default=False)

# ---- CSRF / CORS / Cookies (read from ECL_* envs, with safe defaults) ----
CSRF_TRUSTED_ORIGINS = json.loads(os.environ.get("ECL_DJANGO_CSRF_TRUSTED_ORIGINS", default="[]"))
CORS_ALLOWED_ORIGINS = json.loads(os.environ.get("ECL_DJANGO_CORS_ALLOWED_ORIGINS", default="[]"))
CORS_ALLOW_CREDENTIALS = env.bool("ECL_CORS_ALLOW_CREDENTIALS", default=True)

SESSION_COOKIE_SECURE = env.bool("ECL_SESSION_COOKIE_SECURE", default=True)
CSRF_COOKIE_SECURE = env.bool("ECL_CSRF_COOKIE_SECURE", default=True)

# Django expects strings: 'Lax' | 'Strict' | 'None'
SESSION_COOKIE_SAMESITE = env.str("ECL_SESSION_COOKIE_SAMESITE", default="None")
CSRF_COOKIE_SAMESITE   = env.str("ECL_CSRF_COOKIE_SAMESITE",   default="None")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "account.User"

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = json.loads(os.environ.get("ECL_DJANGO_CORS_ALLOWED_ORIGINS", default="[]"))

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.TokenAuthentication"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

# SWAGGER

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {"Token": {"type": "apiKey", "name": "Authorization", "in": "header"}},
    "USE_SESSION_AUTH": False,
}

# CELERY
CELERY_BROKER_URL = env.str("ECL_CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env.str("ECL_CELERY_RESULT_BACKEND")

if CELERY_BROKER_URL.startswith("rediss://"):
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}
    CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}

CELERY_TIMEZONE = env.str("ECL_CELERY_TIMEZONE")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CATALOG_LANGUAGE_MODEL_PROVIDERS = {
    "OpenAI": "enthusiast_model_openai.OpenAILanguageModelProvider",
}

CATALOG_EMBEDDING_PROVIDERS = {
    "OpenAI": "enthusiast_model_openai.OpenAIEmbeddingProvider",
}

# Configuration of installed plugins {plugin_name: plugin_path}
CATALOG_PRODUCT_SOURCE_PLUGINS = {
    "Sample Product Source": "enthusiast_source_sample.SampleProductSource",
}
CATALOG_DOCUMENT_SOURCE_PLUGINS = {
    "Sample Document Source": "enthusiast_source_sample.SampleDocumentSource",
}
CATALOG_MODELS = {
    "user": "account.models.User",
    "message": "agent.models.Message",
    "conversation": "agent.models.Conversation",
    "data_set": "catalog.models.DataSet",
    "document_chunk": "catalog.models.DocumentChunk",
    "product": "catalog.models.Product",
    "product_chunk": "catalog.models.ProductContentChunk",
    "agent": "agent.models.Agent",
}

AGENT_TOOLS = {
    "Create Answer Tool": "agent.tools.create_answer_tool.CreateAnswerTool",
}

AVAILABLE_AGENTS: dict[str, dict[str, str]] = {
    "question_answer_agent": {
        "name": "Question Answer Agent",
        "agent_directory_path": "agent.core.agents.tool_calling_agent",
    },
}

DEFAULT_AGENT: dict = {
    "type": "question_answer_agent",
    "name": "Default Agent",
    "description": "Default agent",
    "config": {"tools": [{}], "agent_args": {}, "prompt_input": {}, "prompt_extension": {}},
}

FILE_PARSER_CLASSES: dict[tuple[str] : str] = {
    (".txt",): "enthusiast_file_parsers.text.PlainTextFileParser",
    (".pdf",): "enthusiast_file_parsers.pdf.PDFFileParser",
    (
        ".jpg",
        ".jpeg",
        ".png",
    ): "enthusiast_file_parsers.image.ImageFileParser",
}

SERVICE_ACCOUNT_DOMAIN = env.str("SERVICE_ACCOUNT_DOMAIN", "enthusiast.internal")

# Analytics Configuration
ANALYTICS_CONFIG = {
    # Enable/disable local ML models (Stage 2 evaluators)
    # Set to False if you don't want to use Detoxify and Sentence-BERT
    "enable_local_models": True,

    # Enable/disable LLM judges (Stage 3 evaluators)
    # Set to False to save on API costs
    "enable_llm_judges": True,

    # Sampling rate for LLM judges (0.0 to 1.0)
    # Only evaluate this % of messages with LLM judges to control costs
    "llm_sampling_rate": 0.1,

    # Async evaluation (run via Celery)
    # Set to False for synchronous evaluation (useful for testing)
    "async_evaluation": True,

    # OpenAI configuration for LLM judges
    "openai_api_key": env.str("OPENAI_API_KEY", ""),
    "llm_judge_model": "gpt-4o-mini",
    "llm_judge_temperature": 0.0,
}

from .settings_override import *  # noqa
