services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=enthusiast
      - POSTGRES_PASSWORD=enthusiast
      - POSTGRES_DB=enthusiast
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.development
    volumes:
      - ./frontend/src:/app/src
    environment:
      - PORT=10001
      - VITE_API_BASE=http://localhost:10000
      - VITE_WS_BASE=ws://localhost:10000
    ports:
      - "10001:10001"
  api:
    build:
      context: .
      dockerfile: server/Dockerfile.development
    volumes:
      - ./server:/app
      - ./plugins/enthusiast-common/enthusiast_common:/usr/local/lib/python3.12/site-packages/enthusiast_common
      - ./server/plugins/enthusiast-source-dermlax/enthusiast_source_dermlax:/usr/local/lib/python3.12/site-packages/enthusiast_source_dermlax
      - ./plugins/enthusiast-source-sample/enthusiast_source_sample:/usr/local/lib/python3.12/site-packages/enthusiast_source_sample
      - ./plugins/enthusiast-model-openai/enthusiast_model_openai:/usr/local/lib/python3.12/site-packages/enthusiast_model_openai
      - ./server/plugins/enthusiast-source-custom/enthusiast_source_custom:/usr/local/lib/python3.12/site-packages/enthusiast_source_custom
    ports:
      - "10000:10000"
    env_file:
      - ./server/.env
    environment:
      - PORT=10000
      - RUN_MIGRATIONS=True
    depends_on:
      - postgres
      - redis
  worker:
    build:
      context: .
      dockerfile: server/Dockerfile.development
    volumes:
      - ./server:/app
      - ./plugins/enthusiast-common/enthusiast_common:/usr/local/lib/python3.12/site-packages/enthusiast_common
      - ./server/plugins/enthusiast-source-dermlax/enthusiast_source_dermlax:/usr/local/lib/python3.12/site-packages/enthusiast_source_dermlax
      - ./plugins/enthusiast-source-sample/enthusiast_source_sample:/usr/local/lib/python3.12/site-packages/enthusiast_source_sample
      - ./plugins/enthusiast-model-openai/enthusiast_model_openai:/usr/local/lib/python3.12/site-packages/enthusiast_model_openai
      - ./server/plugins/enthusiast-source-custom/enthusiast_source_custom:/usr/local/lib/python3.12/site-packages/enthusiast_source_custom
    env_file:
      - ./server/.env
    environment:
      - RUN_MIGRATIONS=False
      - RUN_WORKER=True
    depends_on:
      - postgres
      - redis