# Generated by Django 5.2.4 on 2026-03-02 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0017_alter_agent_options_agent_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('count', models.IntegerField()),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_daily_metrics',
                'ordering': ['-date', 'metric_name'],
                'indexes': [models.Index(fields=['date', 'metric_name'], name='analytics_d_date_38a8a7_idx'), models.Index(fields=['agent_id', 'date'], name='analytics_d_agent_i_b2c5f7_idx'), models.Index(fields=['date', 'agent_id', 'metric_name'], name='analytics_d_date_0a350e_idx')],
                'unique_together': {('date', 'metric_name', 'agent_id', 'model', 'country', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analytics_evaluation_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='analytics_e_status_ce389f_idx'), models.Index(fields=['job_type', 'status'], name='analytics_e_job_typ_2db572_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('count', models.IntegerField(default=1)),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('agent_version', models.IntegerField(default=1)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_metrics', to='agent.conversation')),
            ],
            options={
                'db_table': 'analytics_session_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['conversation', 'metric_name'], name='analytics_s_convers_c1faac_idx'), models.Index(fields=['agent_id', 'metric_name'], name='analytics_s_agent_i_2f88bd_idx'), models.Index(fields=['timestamp'], name='analytics_s_timesta_f88944_idx')],
            },
        ),
        migrations.CreateModel(
            name='TurnMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('agent_version', models.IntegerField(default=1)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_metrics', to='agent.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agent.message')),
            ],
            options={
                'db_table': 'analytics_turn_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['conversation', 'metric_name'], name='analytics_t_convers_2531fc_idx'), models.Index(fields=['metric_name', 'timestamp'], name='analytics_t_metric__116186_idx'), models.Index(fields=['agent_id', 'timestamp'], name='analytics_t_agent_i_ec8eb6_idx')],
            },
        ),
    ]
