# Generated by Django 5.2.4 on 2026-02-20 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_conversationfile_llm_content'),
        ('catalog', '0009_alter_product_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='agent',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='agent',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='total_conversations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(blank=True, default='tool_calling', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status', 'deleted_at'], name='agent_agent_status_c2e073_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['created_at'], name='agent_agent_created_2227df_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['dataset', 'status'], name='agent_agent_dataset_b2a2d3_idx'),
        ),
    ]
