# Generated by Django 5.2.4 on 2026-03-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_alter_agent_options_agent_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
